codecov:
  token: 343b7418-40f9-476b-acad-1fff73687813
  
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

