// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// greedy_align_cpp
List greedy_align_cpp(NumericVector enh_dists, NumericVector con_dists, double tolerance, double keylock_tol);
RcppExport SEXP _epiRomics_greedy_align_cpp(SEXP enh_distsSEXP, SEXP con_distsSEXP, SEXP toleranceSEXP, SEXP keylock_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type enh_dists(enh_distsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type con_dists(con_distsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type keylock_tol(keylock_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_align_cpp(enh_dists, con_dists, tolerance, keylock_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_epiRomics_greedy_align_cpp", (DL_FUNC) &_epiRomics_greedy_align_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_epiRomics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
