# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Greedy distance-based peak alignment (C++ implementation)
#'
#' Given enhancer distances and contact distances from their respective
#' folding boundaries, finds greedy matching of closest pairs within tolerance.
#'
#' @param enh_dists numeric vector of enhancer peak distances from boundary
#' @param con_dists numeric vector of contact peak distances from boundary
#' @param tolerance maximum delta for a pair to be considered aligned
#' @param keylock_tol tighter tolerance for key-lock designation
#' @return List with: n_aligned, aligned_enh (1-based), aligned_con (1-based),
#'         best_delta, is_key_lock
greedy_align_cpp <- function(enh_dists, con_dists, tolerance, keylock_tol) {
    .Call(`_epiRomics_greedy_align_cpp`, enh_dists, con_dists, tolerance, keylock_tol)
}

