# This is a basic workflow to help you get started with Actions


# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master


name: cache-dependencies

jobs:
  cache-dependencies:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    - uses: actions/cache@v2
    if: startsWith(runner.os, 'Linux')
     with:
      path: ~/.local/share/renv
      key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
      restore-keys: |
        ${{ runner.os }}-renv-

